insert into vegfinder_city (id,name,state_id) values (76,'Ambikapur',5);
insert into vegfinder_city (id,name,state_id) values (77,'Bhilai',5);
insert into vegfinder_city (id,name,state_id) values (78,'Bilaspur',5);
insert into vegfinder_city (id,name,state_id) values (79,'Dhamtari',5);
insert into vegfinder_city (id,name,state_id) values (80,'Durg',5);
insert into vegfinder_city (id,name,state_id) values (81,'Jagdalpur',5);
insert into vegfinder_city (id,name,state_id) values (82,'Raipur',5);
insert into vegfinder_city (id,name,state_id) values (83,'Rajnandgaon',5);

insert into vegfinder_city (id,name,state_id) values (84,'Madgaon',6);
insert into vegfinder_city (id,name,state_id) values (85,'Panaji',6);

insert into vegfinder_city (id,name,state_id) values (86,'Adoni',7);
insert into vegfinder_city (id,name,state_id) values (87,'Amaravati',7);
insert into vegfinder_city (id,name,state_id) values (88,'Anantapur',7);
insert into vegfinder_city (id,name,state_id) values (89,'Chandragiri',7);
insert into vegfinder_city (id,name,state_id) values (90,'Chittoor',7);
insert into vegfinder_city (id,name,state_id) values (91,'Dowlaiswaram',7);
insert into vegfinder_city (id,name,state_id) values (92,'Eluru',7);
insert into vegfinder_city (id,name,state_id) values (93,'Guntur',7);
insert into vegfinder_city (id,name,state_id) values (94,'Kadapa',7);
insert into vegfinder_city (id,name,state_id) values (95,'Kakinada',7);
insert into vegfinder_city (id,name,state_id) values (96,'Kurnool',7);
insert into vegfinder_city (id,name,state_id) values (97,'Machilipatnam',7);
insert into vegfinder_city (id,name,state_id) values (98,'Nagarjunakoṇḍa',7);
insert into vegfinder_city (id,name,state_id) values (99,'Rajahmundry',7);
insert into vegfinder_city (id,name,state_id) values (100,'Srikakulam',7);
insert into vegfinder_city (id,name,state_id) values (101,'Tirupati',7);
insert into vegfinder_city (id,name,state_id) values (102,'Vijayawada',7);
insert into vegfinder_city (id,name,state_id) values (103,'Visakhapatnam',7);
insert into vegfinder_city (id,name,state_id) values (104,'Vizianagaram',7);
insert into vegfinder_city (id,name,state_id) values (105,'Yemmiganur',7);

insert into vegfinder_city (id,name,state_id) values (106,'Ambala',8);
insert into vegfinder_city (id,name,state_id) values (107,'Bhiwani',8);
insert into vegfinder_city (id,name,state_id) values (108,'Chandigarh',8);
insert into vegfinder_city (id,name,state_id) values (109,'Faridabad',8);
insert into vegfinder_city (id,name,state_id) values (110,'Firozpur Jhirka',8);
insert into vegfinder_city (id,name,state_id) values (111,'Gurugram',8);
insert into vegfinder_city (id,name,state_id) values (112,'Hansi',8);
insert into vegfinder_city (id,name,state_id) values (113,'Hisar',8);
insert into vegfinder_city (id,name,state_id) values (114,'Jind',8);
insert into vegfinder_city (id,name,state_id) values (115,'Kaithal',8);
insert into vegfinder_city (id,name,state_id) values (116,'Karnal',8);
insert into vegfinder_city (id,name,state_id) values (117,'Kurukshetra',8);
insert into vegfinder_city (id,name,state_id) values (118,'Panipat',8);
insert into vegfinder_city (id,name,state_id) values (119,'Pehowa',8);
insert into vegfinder_city (id,name,state_id) values (120,'Rewari',8);
insert into vegfinder_city (id,name,state_id) values (121,'Rohtak',8);
insert into vegfinder_city (id,name,state_id) values (122,'Sirsa',8);
insert into vegfinder_city (id,name,state_id) values (123,'Sonipat',8);

insert into vegfinder_city (id,name,state_id) values (124,'Bilaspur',9);
insert into vegfinder_city (id,name,state_id) values (125,'Chamba',9);
insert into vegfinder_city (id,name,state_id) values (126,'Dalhousie',9);
insert into vegfinder_city (id,name,state_id) values (127,'Dharmshala',9);
insert into vegfinder_city (id,name,state_id) values (128,'Hamirpur',9);
insert into vegfinder_city (id,name,state_id) values (129,'Kangra',9);
insert into vegfinder_city (id,name,state_id) values (130,'Kullu',9);
insert into vegfinder_city (id,name,state_id) values (131,'Mandi',9);
insert into vegfinder_city (id,name,state_id) values (132,'Nahan',9);
insert into vegfinder_city (id,name,state_id) values (133,'Shimla',9);
insert into vegfinder_city (id,name,state_id) values (134,'Una',9);

insert into vegfinder_city (id,name,state_id) values (135,'Bokaro',10);
insert into vegfinder_city (id,name,state_id) values (136,'Chaibasa',10);
insert into vegfinder_city (id,name,state_id) values (137,'Deoghar',10);
insert into vegfinder_city (id,name,state_id) values (138,'Dhanbad',10);
insert into vegfinder_city (id,name,state_id) values (139,'Dumka',10);
insert into vegfinder_city (id,name,state_id) values (140,'Giridih',10);
insert into vegfinder_city (id,name,state_id) values (141,'Hazaribag',10);
insert into vegfinder_city (id,name,state_id) values (142,'Jamshedpur',10);
insert into vegfinder_city (id,name,state_id) values (143,'Jharia',10);
insert into vegfinder_city (id,name,state_id) values (144,'Rajmahal',10);
insert into vegfinder_city (id,name,state_id) values (145,'Ranchi',10);
insert into vegfinder_city (id,name,state_id) values (146,'Saraikela',10);

insert into vegfinder_city (id,name,state_id) values (147,'Badami',11);
insert into vegfinder_city (id,name,state_id) values (148,'Ballari',11);
insert into vegfinder_city (id,name,state_id) values (149,'Bengaluru',11);
insert into vegfinder_city (id,name,state_id) values (150,'Belagavi',11);
insert into vegfinder_city (id,name,state_id) values (151,'Bhadravati',11);
insert into vegfinder_city (id,name,state_id) values (152,'Bidar',11);
insert into vegfinder_city (id,name,state_id) values (153,'Chikkamagaluru',11);
insert into vegfinder_city (id,name,state_id) values (154,'Chitradurga',11);
insert into vegfinder_city (id,name,state_id) values (155,'Davangere',11);
insert into vegfinder_city (id,name,state_id) values (156,'Halebid',11);
insert into vegfinder_city (id,name,state_id) values (157,'Hassan',11);
insert into vegfinder_city (id,name,state_id) values (158,'Hubballi-Dharwad',11);
insert into vegfinder_city (id,name,state_id) values (159,'Kalaburagi',11);
insert into vegfinder_city (id,name,state_id) values (160,'Kolar',11);
insert into vegfinder_city (id,name,state_id) values (161,'Madikeri',11);
insert into vegfinder_city (id,name,state_id) values (162,'Mandya',11);
insert into vegfinder_city (id,name,state_id) values (163,'Mangaluru',11);
insert into vegfinder_city (id,name,state_id) values (164,'Mysuru',11);
insert into vegfinder_city (id,name,state_id) values (165,'Raichur',11);
insert into vegfinder_city (id,name,state_id) values (166,'Shivamogga',11);
insert into vegfinder_city (id,name,state_id) values (167,'Shravanabelagola',11);
insert into vegfinder_city (id,name,state_id) values (168,'Shrirangapattana',11);
insert into vegfinder_city (id,name,state_id) values (169,'Tumakuru',11);
insert into vegfinder_city (id,name,state_id) values (170,'Vijayapura',11);

insert into vegfinder_city (id,name,state_id) values (171,'Alappuzha',12);
insert into vegfinder_city (id,name,state_id) values (172,'Vatakara',12);
insert into vegfinder_city (id,name,state_id) values (173,'Idukki',12);
insert into vegfinder_city (id,name,state_id) values (174,'Kannur',12);
insert into vegfinder_city (id,name,state_id) values (175,'Kochi',12);
insert into vegfinder_city (id,name,state_id) values (176,'Kollam',12);
insert into vegfinder_city (id,name,state_id) values (177,'Kottayam',12);
insert into vegfinder_city (id,name,state_id) values (178,'Kozhikode',12);
insert into vegfinder_city (id,name,state_id) values (179,'Mattancheri',12);
insert into vegfinder_city (id,name,state_id) values (180,'Palakkad',12);
insert into vegfinder_city (id,name,state_id) values (181,'Thalassery',12);
insert into vegfinder_city (id,name,state_id) values (182,'Thiruvananthapuram',12);
insert into vegfinder_city (id,name,state_id) values (183,'Thrissur',12);

insert into vegfinder_city (id,name,state_id) values (184,'Balaghat',13);
insert into vegfinder_city (id,name,state_id) values (185,'Barwani',13);
insert into vegfinder_city (id,name,state_id) values (186,'Betul',13);
insert into vegfinder_city (id,name,state_id) values (187,'Bharhut',13);
insert into vegfinder_city (id,name,state_id) values (188,'Bhind',13);
insert into vegfinder_city (id,name,state_id) values (189,'Bhojpur',13);
insert into vegfinder_city (id,name,state_id) values (190,'Bhopal',13);
insert into vegfinder_city (id,name,state_id) values (191,'Burhanpur',13);
insert into vegfinder_city (id,name,state_id) values (192,'Chhatarpur',13);
insert into vegfinder_city (id,name,state_id) values (193,'Chhindwara',13);
insert into vegfinder_city (id,name,state_id) values (194,'Damoh',13);
insert into vegfinder_city (id,name,state_id) values (195,'Datia',13);
insert into vegfinder_city (id,name,state_id) values (196,'Dewas',13);
insert into vegfinder_city (id,name,state_id) values (197,'Dhar',13);
insert into vegfinder_city (id,name,state_id) values (198,'Dr. Ambedkar Nagar (Mhow)',13);
insert into vegfinder_city (id,name,state_id) values (199,'Guna',13);
insert into vegfinder_city (id,name,state_id) values (200,'Gwalior',13);
insert into vegfinder_city (id,name,state_id) values (201,'Hoshangabad',13);
insert into vegfinder_city (id,name,state_id) values (202,'Indore',13);
insert into vegfinder_city (id,name,state_id) values (203,'Itarsi',13);
insert into vegfinder_city (id,name,state_id) values (204,'Jabalpur',13);
insert into vegfinder_city (id,name,state_id) values (205,'Jhabua',13);
insert into vegfinder_city (id,name,state_id) values (206,'Khajuraho',13);
insert into vegfinder_city (id,name,state_id) values (207,'Khandwa',13);
insert into vegfinder_city (id,name,state_id) values (208,'Khargone',13);
insert into vegfinder_city (id,name,state_id) values (209,'Maheshwar',13);
insert into vegfinder_city (id,name,state_id) values (210,'Mandla',13);
insert into vegfinder_city (id,name,state_id) values (211,'Mandsaur',13);
insert into vegfinder_city (id,name,state_id) values (212,'Morena',13);
insert into vegfinder_city (id,name,state_id) values (213,'Murwara',13);
insert into vegfinder_city (id,name,state_id) values (214,'Narsimhapur',13);
insert into vegfinder_city (id,name,state_id) values (215,'Narsinghgarh',13);
insert into vegfinder_city (id,name,state_id) values (216,'Narwar',13);
insert into vegfinder_city (id,name,state_id) values (217,'Neemuch',13);
insert into vegfinder_city (id,name,state_id) values (218,'Nowgong',13);
insert into vegfinder_city (id,name,state_id) values (219,'Orchha',13);
insert into vegfinder_city (id,name,state_id) values (220,'Panna',13);
insert into vegfinder_city (id,name,state_id) values (221,'Raisen',13);
insert into vegfinder_city (id,name,state_id) values (222,'Rajgarh',13);
insert into vegfinder_city (id,name,state_id) values (223,'Ratlam',13);
insert into vegfinder_city (id,name,state_id) values (224,'Rewa',13);
insert into vegfinder_city (id,name,state_id) values (225,'Sagar',13);
insert into vegfinder_city (id,name,state_id) values (226,'Sarangpur',13);
insert into vegfinder_city (id,name,state_id) values (227,'Satna',13);
insert into vegfinder_city (id,name,state_id) values (228,'Sehore',13);
insert into vegfinder_city (id,name,state_id) values (229,'Seoni',13);
insert into vegfinder_city (id,name,state_id) values (230,'Shahdol',13);
insert into vegfinder_city (id,name,state_id) values (231,'Shajapur',13);
insert into vegfinder_city (id,name,state_id) values (232,'Sheopur',13);
insert into vegfinder_city (id,name,state_id) values (233,'Shivpuri',13);
insert into vegfinder_city (id,name,state_id) values (234,'Ujjain',13);
insert into vegfinder_city (id,name,state_id) values (235,'Vidisha',13);

insert into vegfinder_city (id,name,state_id) values (236,'Ahmadnagar',14);
insert into vegfinder_city (id,name,state_id) values (237,'Akola',14);
insert into vegfinder_city (id,name,state_id) values (238,'Amravati',14);
insert into vegfinder_city (id,name,state_id) values (239,'Aurangabad',14);
insert into vegfinder_city (id,name,state_id) values (240,'Bhandara',14);
insert into vegfinder_city (id,name,state_id) values (241,'Bhusawal',14);
insert into vegfinder_city (id,name,state_id) values (242,'Bid',14);
insert into vegfinder_city (id,name,state_id) values (243,'Buldhana',14);
insert into vegfinder_city (id,name,state_id) values (244,'Chandrapur',14);
insert into vegfinder_city (id,name,state_id) values (245,'Daulatabad',14);
insert into vegfinder_city (id,name,state_id) values (246,'Dhule',14);
insert into vegfinder_city (id,name,state_id) values (247,'Jalgaon',14);
insert into vegfinder_city (id,name,state_id) values (248,'Kalyan',14);
insert into vegfinder_city (id,name,state_id) values (249,'Karli',14);
insert into vegfinder_city (id,name,state_id) values (250,'Kolhapur',14);
insert into vegfinder_city (id,name,state_id) values (251,'Mahabaleshwar',14);
insert into vegfinder_city (id,name,state_id) values (252,'Malegaon',14);
insert into vegfinder_city (id,name,state_id) values (253,'Matheran',14);
insert into vegfinder_city (id,name,state_id) values (254,'Mumbai',14);
insert into vegfinder_city (id,name,state_id) values (255,'Nagpur',14);
insert into vegfinder_city (id,name,state_id) values (256,'Nanded',14);
insert into vegfinder_city (id,name,state_id) values (257,'Nashik',14);
insert into vegfinder_city (id,name,state_id) values (258,'Osmanabad',14);
insert into vegfinder_city (id,name,state_id) values (259,'Pandharpur',14);
insert into vegfinder_city (id,name,state_id) values (260,'Parbhani',14);
insert into vegfinder_city (id,name,state_id) values (261,'Pune',14);
insert into vegfinder_city (id,name,state_id) values (262,'Ratnagiri',14);
insert into vegfinder_city (id,name,state_id) values (263,'Sangli',14);
insert into vegfinder_city (id,name,state_id) values (264,'Satara',14);
insert into vegfinder_city (id,name,state_id) values (265,'Sevagram',14);
insert into vegfinder_city (id,name,state_id) values (266,'Solapur',14);
insert into vegfinder_city (id,name,state_id) values (267,'Thane',14);
insert into vegfinder_city (id,name,state_id) values (268,'Ulhasnagar',14);
insert into vegfinder_city (id,name,state_id) values (269,'Vasai-Virar',14);
insert into vegfinder_city (id,name,state_id) values (270,'Wardha',14);
insert into vegfinder_city (id,name,state_id) values (271,'Yavatmal',14);

insert into vegfinder_city (id,name,state_id) values (272,'Imphal',15);

insert into vegfinder_city (id,name,state_id) values (273,'Cherrapunji',16);
insert into vegfinder_city (id,name,state_id) values (274,'Shillong',16);

insert into vegfinder_city (id,name,state_id) values (275,'Aizawl',17);
insert into vegfinder_city (id,name,state_id) values (276,'Lunglei',17);

insert into vegfinder_city (id,name,state_id) values (277,'Kohima',18);
insert into vegfinder_city (id,name,state_id) values (278,'Mon',18);
insert into vegfinder_city (id,name,state_id) values (279,'Phek',18);
insert into vegfinder_city (id,name,state_id) values (280,'Wokha',18);
insert into vegfinder_city (id,name,state_id) values (281,'Zunheboto',18);

insert into vegfinder_city (id,name,state_id) values (282,'Balangir',19);
insert into vegfinder_city (id,name,state_id) values (283,'Baleshwar',19);
insert into vegfinder_city (id,name,state_id) values (284,'Baripada',19);
insert into vegfinder_city (id,name,state_id) values (285,'Bhubaneshwar',19);
insert into vegfinder_city (id,name,state_id) values (286,'Brahmapur',19);
insert into vegfinder_city (id,name,state_id) values (287,'Cuttack',19);
insert into vegfinder_city (id,name,state_id) values (288,'Dhenkanal',19);
insert into vegfinder_city (id,name,state_id) values (289,'Kendujhar',19);
insert into vegfinder_city (id,name,state_id) values (290,'Konark',19);
insert into vegfinder_city (id,name,state_id) values (291,'Koraput',19);
insert into vegfinder_city (id,name,state_id) values (292,'Paradip',19);
insert into vegfinder_city (id,name,state_id) values (293,'Phulabani',19);
insert into vegfinder_city (id,name,state_id) values (294,'Puri',19);
insert into vegfinder_city (id,name,state_id) values (295,'Sambalpur',19);
insert into vegfinder_city (id,name,state_id) values (296,'Udayagiri',19);

insert into vegfinder_city (id,name,state_id) values (297,'Amritsar',20);
insert into vegfinder_city (id,name,state_id) values (298,'Batala',20);
insert into vegfinder_city (id,name,state_id) values (299,'Chandigarh',20);
insert into vegfinder_city (id,name,state_id) values (300,'Faridkot',20);
insert into vegfinder_city (id,name,state_id) values (301,'Firozpur',20);
insert into vegfinder_city (id,name,state_id) values (302,'Gurdaspur',20);
insert into vegfinder_city (id,name,state_id) values (303,'Hoshiarpur',20);
insert into vegfinder_city (id,name,state_id) values (304,'Jalandhar',20);
insert into vegfinder_city (id,name,state_id) values (305,'Kapurthala',20);
insert into vegfinder_city (id,name,state_id) values (306,'Ludhiana',20);
insert into vegfinder_city (id,name,state_id) values (307,'Nabha',20);
insert into vegfinder_city (id,name,state_id) values (308,'Patiala',20);
insert into vegfinder_city (id,name,state_id) values (309,'Rupnagar',20);
insert into vegfinder_city (id,name,state_id) values (310,'Sangrur',20);

insert into vegfinder_city (id,name,state_id) values (311,'Abu',21);
insert into vegfinder_city (id,name,state_id) values (312,'Ajmer',21);
insert into vegfinder_city (id,name,state_id) values (313,'Alwar',21);
insert into vegfinder_city (id,name,state_id) values (314,'Amer',21);
insert into vegfinder_city (id,name,state_id) values (315,'Barmer',21);
insert into vegfinder_city (id,name,state_id) values (316,'Beawar',21);
insert into vegfinder_city (id,name,state_id) values (317,'Bharatpur',21);
insert into vegfinder_city (id,name,state_id) values (318,'Bhilwara',21);
insert into vegfinder_city (id,name,state_id) values (319,'Bikaner',21);
insert into vegfinder_city (id,name,state_id) values (320,'Bundi',21);
insert into vegfinder_city (id,name,state_id) values (321,'Chittaurgarh',21);
insert into vegfinder_city (id,name,state_id) values (322,'Churu',21);
insert into vegfinder_city (id,name,state_id) values (323,'Dhaulpur',21);
insert into vegfinder_city (id,name,state_id) values (324,'Dungarpur',21);
insert into vegfinder_city (id,name,state_id) values (325,'Ganganagar',21);
insert into vegfinder_city (id,name,state_id) values (326,'Hanumangarh',21);
insert into vegfinder_city (id,name,state_id) values (327,'Jaipur',21);
insert into vegfinder_city (id,name,state_id) values (328,'Jaisalmer',21);
insert into vegfinder_city (id,name,state_id) values (329,'Jalor',21);
insert into vegfinder_city (id,name,state_id) values (330,'Jhalawar',21);
insert into vegfinder_city (id,name,state_id) values (331,'Jhunjhunu',21);
insert into vegfinder_city (id,name,state_id) values (332,'Jodhpur',21);
insert into vegfinder_city (id,name,state_id) values (333,'Kishangarh',21);
insert into vegfinder_city (id,name,state_id) values (334,'Kota',21);
insert into vegfinder_city (id,name,state_id) values (335,'Merta',21);
insert into vegfinder_city (id,name,state_id) values (336,'Nagaur',21);
insert into vegfinder_city (id,name,state_id) values (337,'Nathdwara',21);
insert into vegfinder_city (id,name,state_id) values (338,'Pali',21);
insert into vegfinder_city (id,name,state_id) values (339,'Phalodi',21);
insert into vegfinder_city (id,name,state_id) values (340,'Pushkar',21);
insert into vegfinder_city (id,name,state_id) values (341,'Sawai Madhopur',21);
insert into vegfinder_city (id,name,state_id) values (342,'Shahpura',21);
insert into vegfinder_city (id,name,state_id) values (343,'Sikar',21);
insert into vegfinder_city (id,name,state_id) values (344,'Sirohi',21);
insert into vegfinder_city (id,name,state_id) values (345,'Tonk',21);
insert into vegfinder_city (id,name,state_id) values (346,'Udaipur',21);

insert into vegfinder_city (id,name,state_id) values (347,'Gangtok',22);
insert into vegfinder_city (id,name,state_id) values (348,'Gyalshing',22);
insert into vegfinder_city (id,name,state_id) values (349,'Lachung',22);
insert into vegfinder_city (id,name,state_id) values (350,'Mangan',22);

insert into vegfinder_city (id,name,state_id) values (351,'Arcot',23);
insert into vegfinder_city (id,name,state_id) values (352,'Chengalpattu',23);
insert into vegfinder_city (id,name,state_id) values (353,'Chennai',23);
insert into vegfinder_city (id,name,state_id) values (354,'Chidambaram',23);
insert into vegfinder_city (id,name,state_id) values (355,'Coimbatore',23);
insert into vegfinder_city (id,name,state_id) values (356,'Cuddalore',23);
insert into vegfinder_city (id,name,state_id) values (357,'Dharmapuri',23);
insert into vegfinder_city (id,name,state_id) values (358,'Dindigul',23);
insert into vegfinder_city (id,name,state_id) values (359,'Erode',23);
insert into vegfinder_city (id,name,state_id) values (360,'Kanchipuram',23);
insert into vegfinder_city (id,name,state_id) values (361,'Kanniyakumari',23);
insert into vegfinder_city (id,name,state_id) values (362,'Kodaikanal',23);
insert into vegfinder_city (id,name,state_id) values (363,'Kumbakonam',23);
insert into vegfinder_city (id,name,state_id) values (364,'Madurai',23);
insert into vegfinder_city (id,name,state_id) values (365,'Mamallapuram',23);
insert into vegfinder_city (id,name,state_id) values (366,'Nagappattinam',23);
insert into vegfinder_city (id,name,state_id) values (367,'Nagercoil',23);
insert into vegfinder_city (id,name,state_id) values (368,'Palayamkottai',23);
insert into vegfinder_city (id,name,state_id) values (369,'Pudukkottai',23);
insert into vegfinder_city (id,name,state_id) values (370,'Rajapalayam',23);
insert into vegfinder_city (id,name,state_id) values (371,'Ramanathapuram',23);
insert into vegfinder_city (id,name,state_id) values (372,'Salem',23);
insert into vegfinder_city (id,name,state_id) values (373,'Thanjavur',23);
insert into vegfinder_city (id,name,state_id) values (374,'Tiruchchirappalli',23);
insert into vegfinder_city (id,name,state_id) values (375,'Tirunelveli',23);
insert into vegfinder_city (id,name,state_id) values (376,'Tiruppur',23);
insert into vegfinder_city (id,name,state_id) values (377,'Thoothukudi',23);
insert into vegfinder_city (id,name,state_id) values (378,'Udhagamandalam',23);
insert into vegfinder_city (id,name,state_id) values (379,'Vellore',23);

insert into vegfinder_city (id,name,state_id) values (380,'Hyderabad',24);
insert into vegfinder_city (id,name,state_id) values (381,'Karimnagar',24);
insert into vegfinder_city (id,name,state_id) values (382,'Khammam',24);
insert into vegfinder_city (id,name,state_id) values (383,'Mahbubnagar',24);
insert into vegfinder_city (id,name,state_id) values (384,'Nizamabad',24);
insert into vegfinder_city (id,name,state_id) values (385,'Sangareddi',24);
insert into vegfinder_city (id,name,state_id) values (386,'Warangal',24);

insert into vegfinder_city (id,name,state_id) values (387,'Agartala',25);

insert into vegfinder_city (id,name,state_id) values (388,'Agra',26);
insert into vegfinder_city (id,name,state_id) values (389,'Aligarh',26);
insert into vegfinder_city (id,name,state_id) values (390,'Amroha',26);
insert into vegfinder_city (id,name,state_id) values (391,'Ayodhya',26);
insert into vegfinder_city (id,name,state_id) values (392,'Azamgarh',26);
insert into vegfinder_city (id,name,state_id) values (393,'Bahraich',26);
insert into vegfinder_city (id,name,state_id) values (394,'Ballia',26);
insert into vegfinder_city (id,name,state_id) values (395,'Banda',26);
insert into vegfinder_city (id,name,state_id) values (396,'Bara Banki',26);
insert into vegfinder_city (id,name,state_id) values (397,'Bareilly',26);
insert into vegfinder_city (id,name,state_id) values (398,'Basti',26);
insert into vegfinder_city (id,name,state_id) values (399,'Bijnor',26);
insert into vegfinder_city (id,name,state_id) values (400,'Bithur',26);
insert into vegfinder_city (id,name,state_id) values (401,'Budaun',26);
insert into vegfinder_city (id,name,state_id) values (402,'Bulandshahr',26);
insert into vegfinder_city (id,name,state_id) values (403,'Deoria',26);
insert into vegfinder_city (id,name,state_id) values (404,'Etah',26);
insert into vegfinder_city (id,name,state_id) values (405,'Etawah',26);
insert into vegfinder_city (id,name,state_id) values (406,'Faizabad',26);
insert into vegfinder_city (id,name,state_id) values (407,'Farrukhabad-cum-Fatehgarh',26);
insert into vegfinder_city (id,name,state_id) values (408,'Fatehpur',26);
insert into vegfinder_city (id,name,state_id) values (409,'Fatehpur Sikri',26);
insert into vegfinder_city (id,name,state_id) values (410,'Ghaziabad',26);
insert into vegfinder_city (id,name,state_id) values (411,'Ghazipur',26);
insert into vegfinder_city (id,name,state_id) values (412,'Gonda',26);
insert into vegfinder_city (id,name,state_id) values (413,'Gorakhpur',26);
insert into vegfinder_city (id,name,state_id) values (414,'Hamirpur',26);
insert into vegfinder_city (id,name,state_id) values (415,'Hardoi',26);
insert into vegfinder_city (id,name,state_id) values (416,'Hathras',26);
insert into vegfinder_city (id,name,state_id) values (417,'Jalaun',26);
insert into vegfinder_city (id,name,state_id) values (418,'Jaunpur',26);
insert into vegfinder_city (id,name,state_id) values (419,'Jhansi',26);
insert into vegfinder_city (id,name,state_id) values (420,'Kannauj',26);
insert into vegfinder_city (id,name,state_id) values (421,'Kanpur',26);
insert into vegfinder_city (id,name,state_id) values (422,'Lakhimpur',26);
insert into vegfinder_city (id,name,state_id) values (423,'Lalitpur',26);
insert into vegfinder_city (id,name,state_id) values (424,'Lucknow',26);
insert into vegfinder_city (id,name,state_id) values (425,'Mainpuri',26);
insert into vegfinder_city (id,name,state_id) values (426,'Mathura',26);
insert into vegfinder_city (id,name,state_id) values (427,'Meerut',26);
insert into vegfinder_city (id,name,state_id) values (428,'Mirzapur-Vindhyachal',26);
insert into vegfinder_city (id,name,state_id) values (429,'Moradabad',26);
insert into vegfinder_city (id,name,state_id) values (430,'Muzaffarnagar',26);
insert into vegfinder_city (id,name,state_id) values (431,'Partapgarh',26);
insert into vegfinder_city (id,name,state_id) values (432,'Pilibhit',26);
insert into vegfinder_city (id,name,state_id) values (433,'Prayagraj',26);
insert into vegfinder_city (id,name,state_id) values (434,'Rae Bareli',26);
insert into vegfinder_city (id,name,state_id) values (435,'Rampur',26);
insert into vegfinder_city (id,name,state_id) values (436,'Saharanpur',26);
insert into vegfinder_city (id,name,state_id) values (437,'Sambhal',26);
insert into vegfinder_city (id,name,state_id) values (438,'Shahjahanpur',26);
insert into vegfinder_city (id,name,state_id) values (439,'Sitapur',26);
insert into vegfinder_city (id,name,state_id) values (440,'Sultanpur',26);
insert into vegfinder_city (id,name,state_id) values (441,'Tehri',26);
insert into vegfinder_city (id,name,state_id) values (442,'Varanasi',26);

insert into vegfinder_city (id,name,state_id) values (443,'Almora',27);
insert into vegfinder_city (id,name,state_id) values (444,'Dehra Dun',27);
insert into vegfinder_city (id,name,state_id) values (445,'Haridwar',27);
insert into vegfinder_city (id,name,state_id) values (446,'Mussoorie',27);
insert into vegfinder_city (id,name,state_id) values (447,'Nainital',27);
insert into vegfinder_city (id,name,state_id) values (448,'Pithoragarh',27);

insert into vegfinder_city (id,name,state_id) values (449,'Alipore',28);
insert into vegfinder_city (id,name,state_id) values (450,'Alipur Duar',28);
insert into vegfinder_city (id,name,state_id) values (451,'Asansol',28);
insert into vegfinder_city (id,name,state_id) values (452,'Baharampur',28);
insert into vegfinder_city (id,name,state_id) values (453,'Bally',28);
insert into vegfinder_city (id,name,state_id) values (454,'Balurghat',28);
insert into vegfinder_city (id,name,state_id) values (455,'Bankura',28);
insert into vegfinder_city (id,name,state_id) values (456,'Baranagar',28);
insert into vegfinder_city (id,name,state_id) values (457,'Barasat',28);
insert into vegfinder_city (id,name,state_id) values (458,'Barrackpore',28);
insert into vegfinder_city (id,name,state_id) values (459,'Basirhat',28);
insert into vegfinder_city (id,name,state_id) values (460,'Bhatpara',28);
insert into vegfinder_city (id,name,state_id) values (461,'Bishnupur',28);
insert into vegfinder_city (id,name,state_id) values (462,'Budge Budge',28);
insert into vegfinder_city (id,name,state_id) values (463,'Burdwan',28);
insert into vegfinder_city (id,name,state_id) values (464,'Chandernagore',28);
insert into vegfinder_city (id,name,state_id) values (465,'Darjeeling',28);
insert into vegfinder_city (id,name,state_id) values (466,'Diamond Harbour',28);
insert into vegfinder_city (id,name,state_id) values (467,'Dum Dum',28);
insert into vegfinder_city (id,name,state_id) values (468,'Durgapur',28);
insert into vegfinder_city (id,name,state_id) values (469,'Halisahar',28);
insert into vegfinder_city (id,name,state_id) values (470,'Haora',28);
insert into vegfinder_city (id,name,state_id) values (471,'Hugli',28);
insert into vegfinder_city (id,name,state_id) values (472,'Ingraj Bazar',28);
insert into vegfinder_city (id,name,state_id) values (473,'Jalpaiguri',28);
insert into vegfinder_city (id,name,state_id) values (474,'Kalimpong',28);
insert into vegfinder_city (id,name,state_id) values (475,'Kamarhati',28);
insert into vegfinder_city (id,name,state_id) values (476,'Kanchrapara',28);
insert into vegfinder_city (id,name,state_id) values (477,'Kharagpur',28);
insert into vegfinder_city (id,name,state_id) values (478,'Cooch Behar',28);
insert into vegfinder_city (id,name,state_id) values (479,'Kolkata',28);
insert into vegfinder_city (id,name,state_id) values (480,'Krishnanagar',28);
insert into vegfinder_city (id,name,state_id) values (481,'Malda',28);
insert into vegfinder_city (id,name,state_id) values (482,'Midnapore',28);
insert into vegfinder_city (id,name,state_id) values (483,'Murshidabad',28);
insert into vegfinder_city (id,name,state_id) values (484,'Nabadwip',28);
insert into vegfinder_city (id,name,state_id) values (485,'Palashi',28);
insert into vegfinder_city (id,name,state_id) values (486,'Panihati',28);
insert into vegfinder_city (id,name,state_id) values (487,'Purulia',28);
insert into vegfinder_city (id,name,state_id) values (488,'Raiganj',28);
insert into vegfinder_city (id,name,state_id) values (489,'Santipur',28);
insert into vegfinder_city (id,name,state_id) values (490,'Shantiniketan',28);
insert into vegfinder_city (id,name,state_id) values (491,'Shrirampur',28);
insert into vegfinder_city (id,name,state_id) values (492,'Siliguri',28);
insert into vegfinder_city (id,name,state_id) values (493,'Siuri',28);
insert into vegfinder_city (id,name,state_id) values (494,'Tamluk',28);
insert into vegfinder_city (id,name,state_id) values (495,'Titagarh',28);

insert into vegfinder_city (id,name,state_id) values (496,'Port Blair',29);

insert into vegfinder_city (id,name,state_id) values (497,'Chandigarh',30);

insert into vegfinder_city (id,name,state_id) values (498,'Daman',31);
insert into vegfinder_city (id,name,state_id) values (499,'Silvassa',31);

insert into vegfinder_city (id,name,state_id) values (500,'Diu',32);

insert into vegfinder_city (id,name,state_id) values (501,'Delhi',33);
insert into vegfinder_city (id,name,state_id) values (502,'New Delhi',33);

insert into vegfinder_city (id,name,state_id) values (503,'Anantnag',34);
insert into vegfinder_city (id,name,state_id) values (504,'Baramula',34);
insert into vegfinder_city (id,name,state_id) values (505,'Doda',34);
insert into vegfinder_city (id,name,state_id) values (506,'Gulmarg',34);
insert into vegfinder_city (id,name,state_id) values (507,'Jammu',34);
insert into vegfinder_city (id,name,state_id) values (508,'Kathua',34);
insert into vegfinder_city (id,name,state_id) values (509,'Punch',34);
insert into vegfinder_city (id,name,state_id) values (510,'Rajouri',34);
insert into vegfinder_city (id,name,state_id) values (511,'Srinagar',34);
insert into vegfinder_city (id,name,state_id) values (512,'Udhampur',34);

insert into vegfinder_city (id,name,state_id) values (513,'Kargil',35);
insert into vegfinder_city (id,name,state_id) values (514,'Leh',35);

insert into vegfinder_city (id,name,state_id) values (515,'Lakshadweep',36);

insert into vegfinder_city (id,name,state_id) values (516,'Karaikal',37);
insert into vegfinder_city (id,name,state_id) values (517,'Mahe',37);
insert into vegfinder_city (id,name,state_id) values (518,'Puducherry',37);
insert into vegfinder_city (id,name,state_id) values (519,'Yanam',37);
