insert into vegfinder_state (id,name,country_id) values (1,'Gujarat',1);
insert into vegfinder_state (id,name,country_id) values (2,'Arunachal Pradesh',1);
insert into vegfinder_state (id,name,country_id) values (3,'Assam',1);
insert into vegfinder_state (id,name,country_id) values (4,'Bihar',1);
insert into vegfinder_state (id,name,country_id) values (5,'Chhattisgarh',1);
insert into vegfinder_state (id,name,country_id) values (6,'Goa',1);
insert into vegfinder_state (id,name,country_id) values (7,'Andhra Pradesh',1);
insert into vegfinder_state (id,name,country_id) values (8,'Haryana',1);
insert into vegfinder_state (id,name,country_id) values (9,'Himachal Pradesh',1);
insert into vegfinder_state (id,name,country_id) values (10,'Jharkhand',1);
insert into vegfinder_state (id,name,country_id) values (11,'Karnataka',1);
insert into vegfinder_state (id,name,country_id) values (12,'Kerala',1);
insert into vegfinder_state (id,name,country_id) values (13,'Madhya Pradesh',1);
insert into vegfinder_state (id,name,country_id) values (14,'Maharashtra',1);
insert into vegfinder_state (id,name,country_id) values (15,'Manipur',1);
insert into vegfinder_state (id,name,country_id) values (16,'Meghalaya',1);
insert into vegfinder_state (id,name,country_id) values (17,'Mizoram',1);
insert into vegfinder_state (id,name,country_id) values (18,'Nagaland',1);
insert into vegfinder_state (id,name,country_id) values (19,'Odisha',1);
insert into vegfinder_state (id,name,country_id) values (20,'Punjab',1);
insert into vegfinder_state (id,name,country_id) values (21,'Rajasthan',1);
insert into vegfinder_state (id,name,country_id) values (22,'Sikkim',1);
insert into vegfinder_state (id,name,country_id) values (23,'Tamil Nadu',1);
insert into vegfinder_state (id,name,country_id) values (24,'Telangana',1);
insert into vegfinder_state (id,name,country_id) values (25,'Tripura',1);
insert into vegfinder_state (id,name,country_id) values (26,'Uttar Pradesh',1);
insert into vegfinder_state (id,name,country_id) values (27,'Uttarakhand',1);
insert into vegfinder_state (id,name,country_id) values (28,'West Bengal',1);
insert into vegfinder_state (id,name,country_id) values (29,'Andaman Nicobar Islands',1);
insert into vegfinder_state (id,name,country_id) values (30,'Chandigarh',1);
insert into vegfinder_state (id,name,country_id) values (31,'Dadra Nagar Haveli',1);
insert into vegfinder_state (id,name,country_id) values (32,'Daman Diu',1);
insert into vegfinder_state (id,name,country_id) values (33,'Delhi',1);
insert into vegfinder_state (id,name,country_id) values (34,'Jammu Kashmir',1);
insert into vegfinder_state (id,name,country_id) values (35,'Ladakh',1);
insert into vegfinder_state (id,name,country_id) values (36,'Lakshadweep',1);
insert into vegfinder_state (id,name,country_id) values (37,'Puducherry',1);
