insert into vegfinder_country (id,name) values (1,'India');
insert into vegfinder_country (id,name) values (2,'Afghanistan');
insert into vegfinder_country (id,name) values (3,'Albania');
insert into vegfinder_country (id,name) values (4,'Algeria');
insert into vegfinder_country (id,name) values (5,'Andorra');
insert into vegfinder_country (id,name) values (6,'Angola');
insert into vegfinder_country (id,name) values (7,'Antigua and Barbuda');
insert into vegfinder_country (id,name) values (8,'Argentina');
insert into vegfinder_country (id,name) values (9,'Armenia');
insert into vegfinder_country (id,name) values (10,'Australia');
insert into vegfinder_country (id,name) values (11,'Austria');
insert into vegfinder_country (id,name) values (12,'Azerbaijan');
insert into vegfinder_country (id,name) values (13,'Bahamas');
insert into vegfinder_country (id,name) values (14,'Bahrain');
insert into vegfinder_country (id,name) values (15,'Bangladesh');
insert into vegfinder_country (id,name) values (16,'Barbados');
insert into vegfinder_country (id,name) values (17,'Belarus');
insert into vegfinder_country (id,name) values (18,'Belgium');
insert into vegfinder_country (id,name) values (19,'Belize');
insert into vegfinder_country (id,name) values (20,'Benin');
insert into vegfinder_country (id,name) values (21,'Bhutan');
insert into vegfinder_country (id,name) values (22,'Bolivia');
insert into vegfinder_country (id,name) values (23,'Bosnia and Herzegovina');
insert into vegfinder_country (id,name) values (24,'Botswana');
insert into vegfinder_country (id,name) values (25,'Brazil');
insert into vegfinder_country (id,name) values (26,'Brunei');
insert into vegfinder_country (id,name) values (27,'Bulgaria');
insert into vegfinder_country (id,name) values (28,'Burkina Faso');
insert into vegfinder_country (id,name) values (29,'Burundi');
insert into vegfinder_country (id,name) values (30,'Cabo Verde');
insert into vegfinder_country (id,name) values (31,'Cambodia');
insert into vegfinder_country (id,name) values (32,'Cameroon');
insert into vegfinder_country (id,name) values (33,'Canada');
insert into vegfinder_country (id,name) values (34,'Central African Republic');
insert into vegfinder_country (id,name) values (35,'Chad');
insert into vegfinder_country (id,name) values (36,'Chile');
insert into vegfinder_country (id,name) values (37,'China');
insert into vegfinder_country (id,name) values (38,'Colombia');
insert into vegfinder_country (id,name) values (39,'Comoros');
insert into vegfinder_country (id,name) values (40,'Congo');
insert into vegfinder_country (id,name) values (41,'Costa Rica');
insert into vegfinder_country (id,name) values (42,'Croatia');
insert into vegfinder_country (id,name) values (43,'Cuba');
insert into vegfinder_country (id,name) values (44,'Cyprus');
insert into vegfinder_country (id,name) values (45,'Czechia');
insert into vegfinder_country (id,name) values (46,'Denmark');
insert into vegfinder_country (id,name) values (47,'Djibouti');
insert into vegfinder_country (id,name) values (48,'Dominica');
insert into vegfinder_country (id,name) values (49,'Dominican Republic');
insert into vegfinder_country (id,name) values (50,'East Timor (Timor-Leste)');
insert into vegfinder_country (id,name) values (51,'Ecuador');
insert into vegfinder_country (id,name) values (52,'Egypt');
insert into vegfinder_country (id,name) values (53,'El Salvador');
insert into vegfinder_country (id,name) values (54,'Equatorial Guinea');
insert into vegfinder_country (id,name) values (55,'Eritrea');
insert into vegfinder_country (id,name) values (56,'Estonia');
insert into vegfinder_country (id,name) values (57,'Eswatini');
insert into vegfinder_country (id,name) values (58,'Ethiopia');
insert into vegfinder_country (id,name) values (59,'Fiji');
insert into vegfinder_country (id,name) values (60,'Finland');
insert into vegfinder_country (id,name) values (61,'France');
insert into vegfinder_country (id,name) values (62,'Gabon');
insert into vegfinder_country (id,name) values (63,'Gambia');
insert into vegfinder_country (id,name) values (64,'Georgia');
insert into vegfinder_country (id,name) values (65,'Germany');
insert into vegfinder_country (id,name) values (66,'Ghana');
insert into vegfinder_country (id,name) values (67,'Greece');
insert into vegfinder_country (id,name) values (68,'Grenada');
insert into vegfinder_country (id,name) values (69,'Guatemala');
insert into vegfinder_country (id,name) values (70,'Guinea');
insert into vegfinder_country (id,name) values (71,'Guinea-Bissau');
insert into vegfinder_country (id,name) values (72,'Guyana');
insert into vegfinder_country (id,name) values (73,'Haiti');
insert into vegfinder_country (id,name) values (74,'Honduras');
insert into vegfinder_country (id,name) values (75,'Hungary');
insert into vegfinder_country (id,name) values (76,'Iceland');
insert into vegfinder_country (id,name) values (77,'Indonesia');
insert into vegfinder_country (id,name) values (78,'Iran');
insert into vegfinder_country (id,name) values (79,'Iraq');
insert into vegfinder_country (id,name) values (80,'Ireland');
insert into vegfinder_country (id,name) values (81,'Israel');
insert into vegfinder_country (id,name) values (82,'Italy');
insert into vegfinder_country (id,name) values (83,'Ivory Coast');
insert into vegfinder_country (id,name) values (84,'Jamaica');
insert into vegfinder_country (id,name) values (85,'Japan');
insert into vegfinder_country (id,name) values (86,'Jordan');
insert into vegfinder_country (id,name) values (87,'Kazakhstan');
insert into vegfinder_country (id,name) values (88,'Kenya');
insert into vegfinder_country (id,name) values (89,'Kiribati');
insert into vegfinder_country (id,name) values (90,'Korea, North');
insert into vegfinder_country (id,name) values (91,'Korea, South');
insert into vegfinder_country (id,name) values (92,'Kosovo');
insert into vegfinder_country (id,name) values (93,'Kuwait');
insert into vegfinder_country (id,name) values (94,'Kyrgyzstan');
insert into vegfinder_country (id,name) values (95,'Laos');
insert into vegfinder_country (id,name) values (96,'Latvia');
insert into vegfinder_country (id,name) values (97,'Lebanon');
insert into vegfinder_country (id,name) values (98,'Lesotho');
insert into vegfinder_country (id,name) values (99,'Liberia');
insert into vegfinder_country (id,name) values (100,'Libya');
insert into vegfinder_country (id,name) values (101,'Liechtenstein');
insert into vegfinder_country (id,name) values (102,'Lithuania');
insert into vegfinder_country (id,name) values (103,'Luxembourg');
insert into vegfinder_country (id,name) values (104,'Madagascar');
insert into vegfinder_country (id,name) values (105,'Malawi');
insert into vegfinder_country (id,name) values (106,'Malaysia');
insert into vegfinder_country (id,name) values (107,'Maldives');
insert into vegfinder_country (id,name) values (108,'Mali');
insert into vegfinder_country (id,name) values (109,'Malta');
insert into vegfinder_country (id,name) values (110,'Marshall Islands');
insert into vegfinder_country (id,name) values (111,'Mauritania');
insert into vegfinder_country (id,name) values (112,'Mauritius');
insert into vegfinder_country (id,name) values (113,'Mexico');
insert into vegfinder_country (id,name) values (114,'Micronesia');
insert into vegfinder_country (id,name) values (115,'Moldova');
insert into vegfinder_country (id,name) values (116,'Monaco');
insert into vegfinder_country (id,name) values (117,'Mongolia');
insert into vegfinder_country (id,name) values (118,'Montenegro');
insert into vegfinder_country (id,name) values (119,'Morocco');
insert into vegfinder_country (id,name) values (120,'Mozambique');
insert into vegfinder_country (id,name) values (121,'Myanmar (Burma)');
insert into vegfinder_country (id,name) values (122,'Namibia');
insert into vegfinder_country (id,name) values (123,'Nauru');
insert into vegfinder_country (id,name) values (124,'Nepal');
insert into vegfinder_country (id,name) values (125,'Netherlands');
insert into vegfinder_country (id,name) values (126,'New Zealand');
insert into vegfinder_country (id,name) values (127,'Nicaragua');
insert into vegfinder_country (id,name) values (128,'Niger');
insert into vegfinder_country (id,name) values (129,'Nigeria');
insert into vegfinder_country (id,name) values (130,'North Macedonia');
insert into vegfinder_country (id,name) values (131,'Norway');
insert into vegfinder_country (id,name) values (132,'Oman');
insert into vegfinder_country (id,name) values (133,'Pakistan');
insert into vegfinder_country (id,name) values (134,'Palau');
insert into vegfinder_country (id,name) values (135,'Palestine');
insert into vegfinder_country (id,name) values (136,'Panama');
insert into vegfinder_country (id,name) values (137,'Papua New Guinea');
insert into vegfinder_country (id,name) values (138,'Paraguay');
insert into vegfinder_country (id,name) values (139,'Peru');
insert into vegfinder_country (id,name) values (140,'Philippines');
insert into vegfinder_country (id,name) values (141,'Poland');
insert into vegfinder_country (id,name) values (142,'Portugal');
insert into vegfinder_country (id,name) values (143,'Qatar');
insert into vegfinder_country (id,name) values (144,'Romania');
insert into vegfinder_country (id,name) values (145,'Russia');
insert into vegfinder_country (id,name) values (146,'Rwanda');
insert into vegfinder_country (id,name) values (147,'Saint Kitts and Nevis');
insert into vegfinder_country (id,name) values (148,'Saint Lucia');
insert into vegfinder_country (id,name) values (149,'Saint Vincent and the Grenadines');
insert into vegfinder_country (id,name) values (150,'Samoa');
insert into vegfinder_country (id,name) values (151,'San Marino');
insert into vegfinder_country (id,name) values (152,'Sao Tome and Principe');
insert into vegfinder_country (id,name) values (153,'Saudi Arabia');
insert into vegfinder_country (id,name) values (154,'Senegal');
insert into vegfinder_country (id,name) values (155,'Serbia');
insert into vegfinder_country (id,name) values (156,'Seychelles');
insert into vegfinder_country (id,name) values (157,'Sierra Leone');
insert into vegfinder_country (id,name) values (158,'Singapore');
insert into vegfinder_country (id,name) values (159,'Slovakia');
insert into vegfinder_country (id,name) values (160,'Slovenia');
insert into vegfinder_country (id,name) values (161,'Solomon Islands');
insert into vegfinder_country (id,name) values (162,'Somalia');
insert into vegfinder_country (id,name) values (163,'South Africa');
insert into vegfinder_country (id,name) values (164,'South Sudan');
insert into vegfinder_country (id,name) values (165,'Spain');
insert into vegfinder_country (id,name) values (166,'Sri Lanka');
insert into vegfinder_country (id,name) values (167,'Sudan');
insert into vegfinder_country (id,name) values (168,'Suriname');
insert into vegfinder_country (id,name) values (169,'Sweden');
insert into vegfinder_country (id,name) values (170,'Switzerland');
insert into vegfinder_country (id,name) values (171,'Syria');
insert into vegfinder_country (id,name) values (172,'Taiwan');
insert into vegfinder_country (id,name) values (173,'Tajikistan');
insert into vegfinder_country (id,name) values (174,'Tanzania');
insert into vegfinder_country (id,name) values (175,'Thailand');
insert into vegfinder_country (id,name) values (176,'Togo');
insert into vegfinder_country (id,name) values (177,'Tonga');
insert into vegfinder_country (id,name) values (178,'Trinidad and Tobago');
insert into vegfinder_country (id,name) values (179,'Tunisia');
insert into vegfinder_country (id,name) values (180,'Turkey');
insert into vegfinder_country (id,name) values (181,'Turkmenistan');
insert into vegfinder_country (id,name) values (182,'Tuvalu');
insert into vegfinder_country (id,name) values (183,'Uganda');
insert into vegfinder_country (id,name) values (184,'Ukraine');
insert into vegfinder_country (id,name) values (185,'United Arab Emirates');
insert into vegfinder_country (id,name) values (186,'United Kingdom');
insert into vegfinder_country (id,name) values (187,'United States');
insert into vegfinder_country (id,name) values (188,'Uruguay');
insert into vegfinder_country (id,name) values (189,'Uzbekistan');
insert into vegfinder_country (id,name) values (190,'Vanuatu');
insert into vegfinder_country (id,name) values (191,'Vatican City');
insert into vegfinder_country (id,name) values (192,'Venezuela');
insert into vegfinder_country (id,name) values (193,'Vietnam');
insert into vegfinder_country (id,name) values (194,'Yemen');
insert into vegfinder_country (id,name) values (195,'Zambia');
insert into vegfinder_country (id,name) values (196,'Zimbabwe');
insert into vegfinder_country (id,name) values (197,'Zimbabwe');
