# Generated by Django 5.0.1 on 2024-01-31 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegfinder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='block_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='street',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_restaurant', to='vegfinder.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants_in_city', to='vegfinder.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants_in_country', to='vegfinder.country'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Dharmshala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='vegfinder/images')),
                ('block_no', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('rooms', models.BigIntegerField()),
                ('facilties', models.TextField()),
                ('rent', models.BigIntegerField()),
                ('restriction', models.TextField()),
                ('contact', models.BigIntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dharmshala_in_city', to='vegfinder.city')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='dharmshala',
            field=models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_dharmshala', to='vegfinder.dharmshala'),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='vegfinder/images')),
                ('block_no', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('rent', models.BigIntegerField()),
                ('contact', models.BigIntegerField()),
                ('ratings', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels_in_city', to='vegfinder.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels_in_country', to='vegfinder.country')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_hotel', to='vegfinder.hotel'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='store/images')),
                ('contact', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='vegfinder.owner'),
        ),
        migrations.AddField(
            model_name='dharmshala',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dharmshala', to='vegfinder.owner'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='vegfinder.owner'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='vegfinder.country')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels_in_state', to='vegfinder.state'),
        ),
        migrations.AddField(
            model_name='dharmshala',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dharmshala_in_state', to='vegfinder.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='vegfinder.state'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants_in_state', to='vegfinder.state'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vegfinder.userprofile'),
        ),
        migrations.AddField(
            model_name='dharmshala',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vegfinder.userprofile'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vegfinder.userprofile'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vegfinder.userprofile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
