# Generated by Django 5.0.1 on 2024-01-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegfinder', '0003_remove_restaurant_address_restaurant_block_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
